version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.1.0
  eb: circleci/aws-elastic-beanstalk@2.0.1
  # different jobs are calles later in the workflows sections
jobs:
  backend:
    docker:
      - image: "cimg/base:stable"
    executor: node/default
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      # install backend app dependencies
      - run:
          name: Backend Install Dependencies
          command: |
            npm run backend:install
      # build backend app code
      - run:
          name: Backend Build App
          command: |
            npm run backend:build
      # test backend app
      # - run:
      #     name: Backend Test App
      #     command: |
      #       npm run backend:test
      # deploy backend app code
      - run:
          name: Backend Deploy App
          command: |
            npm run backend:deploy
  frontend:
    docker:
      - image: "cimg/base:stable"
    executor: node/default
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      # install frontend app dependencies
      - run:
          name: Frontend Install Dependencies
          command: |
            npm run frontend:install
      # build frontend app code
      - run:
          name: Frontend Build App
          command: |
            npm run frontend:build
      # test frontend app
      # - run:
      #     name: Frontend Test App
      #     command: |
      #       npm run frontend:test
      # deploy frontend app code
      - run:
          name: Frontend Deploy App
          command: |
            npm run frontend:deploy
workflows:
  build_and_deploy:
    jobs:
      - backend
      - frontend
